#!/usr/bin/env python

from sys import argv
from subprocess import check_output
from openai import OpenAI
import os

_, commit_file = argv

instructions = "Generate a concise commit message based on the diff information provided. If there are multiple, unrelated changes, separate them with bullet points. For small or simple changes, only provide a brief title. Avoid using any formatting, code blocks, or indicators like 'Title:' or 'Body:'. Keep it short and straightforward."

instruction_file = os.path.expanduser("~/.commit_message_instructions")
if os.path.exists(instruction_file):
    with open(instruction_file, 'r') as file:
        instructions = file.read().strip()

api_key = os.environ.get("OPENAI_API_KEY")

if not api_key:
    raise ValueError("OPENAI_API_KEY environment variable not found")

client = OpenAI(api_key=api_key.strip())

diff = check_output("git diff --staged", shell=True, text=True)

response = client.responses.create(
    model="gpt-4o",
    instructions=instructions,
    input=diff,
)

with open(commit_file, 'w') as file:
    file.write(response.output_text)
